src/safemail/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

src/safemail/mail/urls.py
from django.urls import path

from . import views

app_name = 'mail'

urlpatterns = [
    path('', views.home, name='home'),
    path('compose/', views.compose, name="compose"),
    path('inbox/', views.inbox, name='inbox'),
    path('sent/', views.sent, name='sent'),
    path('inbox/<pk>/delete/',views.Maildelete.as_view(), name="delete"),
    # path('getin/', views.getin, name="getin"),

]

src/safemail/safemail/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.views.generic.base import TemplateView
from django.conf import settings

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'),{'form_class': 'core/login.html'},),
    path('accounts/', include('accounts.urls')),
    path('', include('mail.urls')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

src/safemail/accounts/models.py
from django.db import models

# Create your models here.

src/safemail/accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

src/safemail/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>{% block title %}Safe mail{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous"></head>
<body>
  <main>

 <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">

          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'mail:compose' %}">compose</a>
          <a class="nav-item nav-link" href="{% url 'mail:inbox' %}">inbox</a>
          <a class="nav-item nav-link" href="{% url 'mail:sent' %}">sent mail</a>

          <a class="nav-item nav-link navbar-right" href="{% url 'logout' %}">logout</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Singup</a>

              <a class="nav-item nav-link navbar-right" href="{% url 'login' %}">login</a>


          {% endif %}



    </div>
  </div>
</nav>  -->

<style>
    body {
        background-image: url({% static 'images/bg.jpg' %}); 
        background-size: cover;
        background-color: rgba(0, 0, 0, 0.5);
        
    }

    .caption {
    width: 100%;
    max-width: 100%;
    position: absolute;
    top: 38%;
    color: white;
    z-index: 1;
    text-transform: uppercase;

}

.caption h1 {
    font-size: 3.8rem;
    font-weight: 700;
    letter-spacing: .3rem;
    text-shadow: .1rem .1rem .8rem black;
    padding-bottom: 2rem;
}

.caption h3 {
    font-size: 2rem;
    text-shadow: .1rem .1rem .5rem black;
    padding-bottom: 1.6rem;
}

.btn-lg {
    text-transform: uppercase;
}


.bg-teal , .btn-teal{
    background-color: #3b6e77 !important;
}

.card {
    margin-top: 12rem !important;
    bottom: 5rem;
    
}

.card-login {
    background-color: rgba(0, 0, 0, 0.3);
    color: white;
    border-radius: 10px;
    /* margin-top: 10rem; */
}

.register {
    margin-top: 8rem;
    margin-bottom: 8rem;
}

.login {
    margin-top: 15rem;
    margin-bottom: 15rem;
}


.in >.container-fluid {
    padding-right: 150px;
    padding-left: 150px; 
    
}

.container-fluid1 {
    min-height: 25vh;
    max-height: 50vh;
}
.card-inbox {
    background-color: rgba(0, 0, 0, 0.07);

}

footer {
    position: fixed;
    bottom: 0;
    width: 100%;
    color: white;
}

@media (max-width: 767px) {
.caption h1 {
    font-size: 2.3rem;
    letter-spacing: .15rem;
    padding-bottom: .5rem;
}

.caption h3 {
    font-size: 1.2rem;
    padding-bottom: 1.2rem;
}

.btn-lg {
    text-transform: uppercase;
}

.in >.container-fluid {
    padding-right: 10px;
    padding-left: 10px; 

}

}

</style>

 <nav class="navbar navbar-expand-sm navbar-dark bg-teal "> 
        <div class="container">
            <a href="{% url 'mail:home' %}" class="navbar-brand">
                <i class="fas fa-mail-bulk"></i> Safe Mail</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#mail-navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mail-navbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-iteam px-3">
                        <a href="{% url 'mail:home' %}" class="nav-link text-white">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-iteam px-3">
                        <a href="{% url 'mail:compose' %}" class="nav-link text-white" >Compose</a>
                    </li>
                    <li class="nav-iteam px-3">
                        <a href="{% url 'mail:inbox' %}" class="nav-link text-white">Inbox</a>
                    </li>
                    <li class="nav-iteam px-3">
                        <a href="{% url 'mail:sent' %}" class="nav-link text-white">Sent</a>
                    </li>
                    <li class="nav-iteam px-3">
                        <a href="{% url 'logout' %}" class="nav-link text-white">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-iteam px-3">
                        <a href="{% url 'accounts:signup' %}" class="nav-link text-white">Sign up</a>
                    </li>
                    <li class="nav-iteam px-3">
                        <a href="{% url 'login' %}" class="nav-link text-white">Login</a>
                    </li>
                    {% endif %}
                    
                </ul>
            </div>
        </div>
    </nav> 


 
    <div class="main">
        
  {% block content %}

    {% endblock %}
</div>
    


  <footer class="p-3 bg-teal text-white text-center mt-3 ">
      <div class="container">
          Copyrights &copy 2021. No right Reserved
      </div>
  </footer>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>



  

  </main>
</body>
</html>

src/safemail/templates/base_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="templates/style.css">
  <title>{% block title %}Safe mail{% endblock %}</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-sm navbar-dark bg-teal fixed-top">
        <div class="container">
            <a href="home.html" class="navbar-brand">
                <i class="fas fa-mail-bulk"></i> Safe Mail</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#mail-navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mail-navbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-iteam px-3">
                        <a href="home.html" class="nav-link text-white">Home</a>
                    </li>
                    <li class="nav-iteam px-3">
                        <a href="#compose-modal" class="nav-link text-white" data-toggle="modal" data-target="#compose-modal">Compose</a>
                    </li>
                    <li class="nav-iteam px-3">
                        <a href="#" class="nav-link text-white">Inbox</a>
                    </li>
                    <li class="nav-iteam px-3">
                        <a href="#" class="nav-link text-white">Sent</a>
                    </li>
                    <li class="nav-iteam px-3">
                        <a href="register.html" class="nav-link text-white">Sign up</a>
                    </li>
                    <li class="nav-iteam px-3">
                        <a href="login.html" class="nav-link text-white">Login</a>
                    </li>
                    <li class="nav-iteam px-3">
                        <a href="#" class="nav-link text-white">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <section class="d-flex align-items-center min-vh-100 py-md-0">
        <div class="modal" id="compose-modal">
            <div class="modal-dialog modal-lg modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header bg-secondary text-white">
                        <h4>New Message</h4>
                        <button class="close" data-dismiss="modal">
                            <i class="fa fa-times-circle"></i>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="form-group">
                              <label for="recipient-name" class="col-form-label">To:</label>
                              <input type="text" class="form-control" id="recipient-name">
                            </div>
                            <div class="form-group">
                                <label for="subject" class="col-form-label">Subject:</label>
                                <input type="text" class="form-control" id="subject">
                              </div>
                            <div class="form-group">
                              <label for="message-text" class="col-form-label">Message:</label>
                              <textarea class="form-control" id="message-text" rows="5"></textarea>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-primary">Send</button>
                    </div>
                </div>
            </div>
        </div>
   </section>

    {% block content %}
      {% endblock %}


    <footer class="p-3 bg-teal text-white text-center mt-3">
        <div class="container">
            Copyrights &copy 2021. No right Reserved
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

src/safemail/templates/compose.html
{% extends 'base.html' %}
{% block title %}Safe mail | Compose{% endblock %}
{% block content %}
  {% comment %} <p> {{sen}} </p>
  <form method="POST" enctype="multipart/form-data"> 
  
    <!-- Security token -->
    {% csrf_token %} 
  
    <!-- Using the formset -->
    <input name=to type="text"> 
    <input name=sub type="text"> 
    <input name=message type="text"> 
      
    <input type="submit" value="Submit"> 
</form>  {% endcomment %}


<div class="container">
            <div class="card">
                <h4 class="card-header bg-teal text-white">New Message</h4>
                <div class="card-body">
                <p> {{sen}} </p>
                    <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %} 
                        <div class="form-group">
                          <label for="recipient-name" class="col-form-label">To:</label>
                          <input type="text" name=to class="form-control" id="recipient-name">
                        </div>
                        <div class="form-group">
                            <label for="subject" class="col-form-label">Subject:</label>
                            <input type="text" name=sub class="form-control" id="subject">
                          </div>
                        <div class="form-group">
                          <label for="message-text" class="col-form-label">Message:</label>
                          <textarea class="form-control" name=message id="message-text" rows="5"></textarea>
                        </div>
                        <button type="submit" value="Submit" class="btn btn-info">Send</button>
                    </form>
                </div>
              </div>
        </div>


{% endblock %}

src/safemail/templates/delete.html
<form method="post">{% csrf_token %} 
	<p>Are you sure you want to delete "{{ object }}"?</p> 
	<input type="submit" value="Confirm"> 
</form> 

src/safemail/templates/getin.html
{% extends 'base.html' %}

{% block content %}
  
  <form method="POST" enctype="multipart/form-data"> 
  
    <!-- Security token -->
    {% csrf_token %} 
  
    <!-- Using the formset -->
    <input name="username" type="text"> 
    <input name="password" type="text"> 
      
    <input type="submit" value="Submit"> 
</form> 
{% endblock %}

src/safemail/templates/inbox.html
{% extends 'base.html' %}
{% block title %}Safe mail | Inbox{% endblock %}

{% block content %}

  <!-- {% for x in obj %}
  {{ x.to}}
  {{ x.sender}}
  {{x.sub}}
  {{ x.message}}
  {{x.pk}}
  <a href=" {{x.pk}}/delete">delete</a>
  <br>
    
  {% endfor %} -->

<div class="in">
<div class="container-fluid">
            <div class="card inb">
                <h4 class="card-header bg-teal text-white">Primary Messages</h4>
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                          <tr scope="row">
                            <th scope="col">From :</th>
                            <th scope="col">Message</th>
                            <th></th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for x in obj %}
                          <tr>
                            <th scope="row">{{ x.sender}}</th>
                            <td>
                                <h6 class="" data-toggle="modal" data-target="#inbox-modal{{x.pk}}">{{x.sub}}</h6>
                            </td>  
                            <td>
                                <span><a href=" {{x.pk}}/delete"><i class="fas fa-trash"></i></a></span>
                            </td>
                          </tr>
                          <div class="modal mt-5" id="inbox-modal{{x.pk}}">
                            <div class="modal-dialog modal-dialog-scrollable modal-xl">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">{{x.sub}}</h5>
                                        <button class="close" data-dismiss="modal">
                                            <i class="fa fa-times-circle"></i>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p class="font-weight-bold">{{ x.sender}} <span class="text-muted">to me :</span></p>
                                        <div class="container-fluid1">
                                            <div class="card-inbox text-justify p-3">
                                              <p>{{x.message}}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                          {% endfor %}
                          
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
      </div>
        
      

{% endblock %}

src/safemail/templates/index.html
{% extends 'base.html' %}
{% block title %}Safe mail {% endblock %}
  
{% block content %}
  <div class="caption text-center">
        <h1>Welcome To Safe Mail</h1>
        <h3>Secure your Communications with Safe Mail</h3>
        <a href="{% url 'accounts:signup' %}" class="btn btn-outline-info btn-lg text-white">Get Started</a>
    </div>
    
    <!-- <a class="btn btn-outline-info btn-lg text-white" herf="#">Get Started</a> -->

{% endblock %}

src/safemail/templates/sent.html
{% extends 'base.html' %}
{% block title %}Safe mail | Sent{% endblock %}

{% block content %}
  {% comment %} {% for x in obj %}
  {{ x.to}}
  {{ x.sender}}
  {{ x.message}}
  <br>

  
  {% endfor %} {% endcomment %}

  <div class="in">
  <div class="container-fluid">
            <div class="card">
                <h4 class="card-header bg-teal text-white">Sent Messages</h4>
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                          <tr scope="row">
                            <th scope="col">To :</th>
                            <th scope="col"></th>
                            <th></th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for x in obj %}
                          <tr>
                            <th scope="row">{{ x.to}}</th>
                            <td data-toggle="modal" data-target="#inbox-modal{{x.pk}}">
                                <h6 class="" >{{x.sub}}</h6>
                            </td>  
                            <td>
                            </td>
                          </tr>
                          <div class="modal mt-5" id="inbox-modal{{x.pk}}">
                            <div class="modal-dialog modal-xl modal-dialog-scrollable">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">{{x.sub}}</h5>
                                        <button class="close" data-dismiss="modal">
                                            <i class="fa fa-times-circle"></i>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p class="font-weight-bold">{{ x.sender}} <span class="text-muted">to {{ x.to}}</span></p>
                                        <div class="container-fluid1">
                                            <div class="card-inbox text-justify p-3">
                                              <p>{{ x.message}}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                          {% endfor %}
                          
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
      </div>
{% endblock %}

src/safemail/templates/signup.html
{% extends 'base.html' %}
{%load crispy_forms_tags %} 
{% block title %} Safe mail| Sign Up{% endblock %}

{% block content %}

{% comment %} <div >
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}

    {{ form.as_p }}
    <button class="btn btn-success" type="submit">Sign up</button>
  </form>
  </div> {% endcomment %}



  <div class="container">
    <div class="row">
        <div class="col-md-7">
        </div>
        <div class="col-md-5">
            <div class="card card-login register">
            <div class="card-body">
                <h2 class="login-card-description text-center">Registration Form</h2>
                <hr>
                <form method="post">
                  {% csrf_token %}
                  {{form|crispy}}
                    
                    <button class="btn btn-teal text-white">Register</button>
                </form>
                <p class="login-card-footer-text">Already have an account? <a href="{% url 'login' %}" class="text-reset">Sign in</a></p>
            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}